

<div class="container">
    <h2>Register</h2>
    <p><?php echo $this->flashSession->output() ?></p>

    <?php echo $this->tag->form("register"); ?>

    <div class="form-group">
        <label for="username">Email</label>
        <?php echo $form->render('email'); ?>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <?php echo $form->render('password'); ?>
    </div>

    <div class="form-group">
        <label for="password">Confirm Password</label>
        <?php echo $form->render('confirm_password'); ?>
    </div>

    <div class="form-group">
        <?php echo $form->render('submit'); ?>
    </div>

    <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
    </form>
    <p>Having Account.
        <?= $this->tag->linkTo('', 'Sign In') ?>
    </p>


</div>