

<div class="container">
    <h2>Login</h2>
    <p><?php echo $this->flashSession->output() ?></p>

    <?php echo $this->tag->form("login"); ?>

    <div class="form-group">
        <label for="username">User name</label>
        <?php echo $form->render('email'); ?>
    </div>

    <div class="form-group">
        <label for="password">Password</label>
        <?php echo $form->render('password'); ?>
    </div>

    <div class="form-group">
        <?php echo $form->render('submit'); ?>
    </div>

    <input type='hidden' name='<?= $this->security->getTokenKey() ?>' value='<?= $this->security->getToken() ?>'/>
    </form>
    <p>Do not have account.
        <?= $this->tag->linkTo('register', 'Sign Up') ?>
    </p>


</div>